// The demo catalog: a gift shop. Shaped for the scenarios the assistant is
// measured on — age bounds, items out of stock, slow delivery, and products
// that need something they do not include.

export type CategorySeed = { slug: string; name: string; isSupply?: boolean }

export type ProductSeed = {
	slug: string
	name: string
	category: string
	priceCents: number
	stock: number
	ageMin: number | null
	ageMax: number | null
	deliveryDays: number
	tags: string[]
	requires?: string[]
	description: string
}

export const categories: CategorySeed[] = [
	{ slug: 'toys', name: 'Toys' },
	{ slug: 'games-puzzles', name: 'Games & Puzzles' },
	{ slug: 'books', name: 'Books' },
	{ slug: 'arts-crafts', name: 'Arts & Crafts' },
	{ slug: 'science', name: 'Science & STEM' },
	{ slug: 'outdoor', name: 'Outdoor' },
	{ slug: 'tech', name: 'Tech' },
	{ slug: 'home', name: 'Home' },
	{ slug: 'essentials', name: 'Essentials', isSupply: true },
]

export const tags: Record<string, string> = {
	'screen-free': 'Screen-free',
	stem: 'STEM',
	creative: 'Creative',
	'for-two-plus': 'For two or more',
	outdoor: 'Outdoor',
	cozy: 'Cozy',
	'battery-powered': 'Battery-powered',
	'first-years': 'First years',
	teens: 'Teens',
	adults: 'Adults',
	travel: 'Travel',
	'gift-wrap': 'Gift wrap',
}

export const products: ProductSeed[] = [
	// Essentials: what other products require, and what a gift is wrapped in.
	{
		slug: 'aa-batteries-8',
		name: 'AA Alkaline Batteries, 8-pack',
		category: 'essentials',
		priceCents: 799,
		stock: 400,
		ageMin: null,
		ageMax: null,
		deliveryDays: 1,
		tags: [],
		description:
			'1.5 V alkaline cells with a ten-year shelf life. Fits remote controls, toys and lanterns.',
	},
	{
		slug: 'aaa-batteries-8',
		name: 'AAA Alkaline Batteries, 8-pack',
		category: 'essentials',
		priceCents: 749,
		stock: 350,
		ageMin: null,
		ageMax: null,
		deliveryDays: 1,
		tags: [],
		description:
			'1.5 V alkaline cells for small devices: walkie-talkies, remotes, coding robots.',
	},
	{
		slug: 'instant-film-20',
		name: 'Instant Film, 20 Shots',
		category: 'essentials',
		priceCents: 1800,
		stock: 120,
		ageMin: null,
		ageMax: null,
		deliveryDays: 2,
		tags: [],
		description:
			'Two packs of ten credit-card-size color prints. Develops in about 90 seconds.',
	},
	{
		slug: 'gift-wrap-kit',
		name: 'Gift Wrap Kit: 3 Sheets, Ribbon, Tags',
		category: 'essentials',
		priceCents: 950,
		stock: 200,
		ageMin: null,
		ageMax: null,
		deliveryDays: 1,
		tags: ['gift-wrap'],
		description:
			'Three 50×70 cm sheets of recycled kraft paper, five meters of cotton ribbon and six tags.',
	},
	{
		slug: 'birthday-card-letterpress',
		name: 'Letterpress Birthday Card',
		category: 'essentials',
		priceCents: 500,
		stock: 180,
		ageMin: null,
		ageMax: null,
		deliveryDays: 1,
		tags: ['gift-wrap'],
		description:
			'Blank inside, printed on 600 gsm cotton paper, with a kraft envelope.',
	},
	{
		slug: 'gift-box-medium',
		name: 'Kraft Gift Box with Tissue, Medium',
		category: 'essentials',
		priceCents: 650,
		stock: 150,
		ageMin: null,
		ageMax: null,
		deliveryDays: 1,
		tags: ['gift-wrap'],
		description:
			'28×22×10 cm magnetic-lid box with two sheets of tissue. Fits a book or a board game.',
	},

	// Toys
	{
		slug: 'rc-stunt-car',
		name: 'Remote Control Stunt Car, 360° Flip',
		category: 'toys',
		priceCents: 3999,
		stock: 25,
		ageMin: 6,
		ageMax: 12,
		deliveryDays: 3,
		tags: ['battery-powered'],
		requires: ['aa-batteries-8', 'aaa-batteries-8'],
		description:
			'Drives on both sides and flips on the spot. The car takes 4 AA, the remote 2 AAA; batteries not included.',
	},
	{
		slug: 'wooden-train-set',
		name: 'Wooden Train Set, 52 Pieces',
		category: 'toys',
		priceCents: 5400,
		stock: 12,
		ageMin: 3,
		ageMax: 7,
		deliveryDays: 5,
		tags: ['screen-free'],
		description:
			'Beech track, a bridge, two magnetic engines and four wagons. Compatible with most wooden track systems.',
	},
	{
		slug: 'plush-fox',
		name: 'Plush Fox, 30 cm',
		category: 'toys',
		priceCents: 2400,
		stock: 40,
		ageMin: 0,
		ageMax: null,
		deliveryDays: 2,
		tags: ['first-years', 'cozy'],
		description:
			'Soft recycled polyester, embroidered eyes, machine washable at 30 °C.',
	},
	{
		slug: 'bricks-fire-station',
		name: 'Building Bricks: Fire Station, 610 Pieces',
		category: 'toys',
		priceCents: 4999,
		stock: 18,
		ageMin: 7,
		ageMax: 12,
		deliveryDays: 3,
		tags: ['creative'],
		description:
			'Three-floor station with a truck, a ladder that extends and four figures. Small parts.',
	},
	{
		slug: 'magnetic-tiles-60',
		name: 'Magnetic Building Tiles, 60 Pieces',
		category: 'toys',
		priceCents: 5900,
		stock: 0,
		ageMin: 3,
		ageMax: 10,
		deliveryDays: 4,
		tags: ['stem', 'creative', 'screen-free'],
		description:
			'Squares and triangles in clear colors that click together at any edge. Riveted, magnets cannot come out.',
	},
	{
		slug: 'stacking-rings',
		name: 'Wooden Stacking Rings',
		category: 'toys',
		priceCents: 1800,
		stock: 35,
		ageMin: 1,
		ageMax: 3,
		deliveryDays: 2,
		tags: ['first-years', 'screen-free'],
		description:
			'Seven maple rings on a rounded peg, water-based paint. Rings too large to swallow.',
	},
	{
		slug: 'walkie-talkies-kids',
		name: 'Kids Walkie-Talkies, 2-pack, 3 km Range',
		category: 'toys',
		priceCents: 2999,
		stock: 30,
		ageMin: 5,
		ageMax: 12,
		deliveryDays: 3,
		tags: ['for-two-plus', 'outdoor', 'battery-powered'],
		requires: ['aaa-batteries-8'],
		description:
			'Push to talk, eight channels, a belt clip. Each unit takes 3 AAA; batteries not included.',
	},
	{
		slug: 'marble-run-120',
		name: 'Marble Run, 120 Pieces',
		category: 'toys',
		priceCents: 4400,
		stock: 14,
		ageMin: 5,
		ageMax: 12,
		deliveryDays: 6,
		tags: ['stem', 'screen-free'],
		description:
			'Towers, funnels, a spiral and a lift, with 30 glass marbles. Small parts.',
	},
	{
		slug: 'wooden-dollhouse',
		name: 'Wooden Dollhouse with Furniture',
		category: 'toys',
		priceCents: 11900,
		stock: 6,
		ageMin: 3,
		ageMax: 9,
		deliveryDays: 8,
		tags: ['screen-free', 'creative'],
		description:
			'Three floors, five rooms, 18 pieces of furniture and a working elevator. Assembled in about 40 minutes.',
	},
	{
		slug: 'bubble-machine',
		name: 'Bubble Machine',
		category: 'toys',
		priceCents: 2200,
		stock: 22,
		ageMin: 3,
		ageMax: null,
		deliveryDays: 2,
		tags: ['outdoor', 'battery-powered'],
		requires: ['aa-batteries-8'],
		description:
			'Blows about 500 bubbles a minute from a 150 ml tank. Takes 4 AA; batteries not included.',
	},

	// Games & Puzzles
	{
		slug: 'island-settlers',
		name: 'Island Settlers: Strategy Board Game',
		category: 'games-puzzles',
		priceCents: 4499,
		stock: 20,
		ageMin: 10,
		ageMax: null,
		deliveryDays: 3,
		tags: ['for-two-plus', 'screen-free'],
		description:
			'Trade, build roads and race to ten points. 3–4 players, about 75 minutes a game.',
	},
	{
		slug: 'forest-rescue',
		name: 'Forest Rescue: Cooperative Game',
		category: 'games-puzzles',
		priceCents: 2900,
		stock: 26,
		ageMin: 6,
		ageMax: null,
		deliveryDays: 2,
		tags: ['for-two-plus', 'screen-free'],
		description:
			'Players win or lose together, putting out fires before the forest burns. 2–5 players, 30 minutes.',
	},
	{
		slug: 'puzzle-1000-world-map',
		name: '1000-Piece Puzzle: Vintage World Map',
		category: 'games-puzzles',
		priceCents: 2100,
		stock: 32,
		ageMin: 12,
		ageMax: null,
		deliveryDays: 2,
		tags: ['cozy', 'screen-free'],
		description:
			'70×50 cm when finished, thick blue-board pieces with a linen finish and no dust in the box.',
	},
	{
		slug: 'floor-puzzle-dinosaurs',
		name: '100-Piece Floor Puzzle: Dinosaurs',
		category: 'games-puzzles',
		priceCents: 1600,
		stock: 28,
		ageMin: 4,
		ageMax: 8,
		deliveryDays: 2,
		tags: ['screen-free'],
		description:
			'90×60 cm with 14 species named on the back of the box. Large pieces for small hands.',
	},
	{
		slug: 'word-rush',
		name: 'Word Rush: Party Card Game',
		category: 'games-puzzles',
		priceCents: 1499,
		stock: 45,
		ageMin: 10,
		ageMax: null,
		deliveryDays: 1,
		tags: ['for-two-plus', 'travel'],
		description:
			'Name three things before the sand runs out. 4–10 players, fits in a coat pocket.',
	},
	{
		slug: 'chess-folding-walnut',
		name: 'Wooden Chess Set, Folding Board',
		category: 'games-puzzles',
		priceCents: 3900,
		stock: 15,
		ageMin: 6,
		ageMax: null,
		deliveryDays: 4,
		tags: ['for-two-plus', 'screen-free'],
		description:
			'40 cm walnut board that folds into a case for the pieces. King height 7.5 cm.',
	},
	{
		slug: 'family-trivia',
		name: 'Family Trivia: 1,200 Questions',
		category: 'games-puzzles',
		priceCents: 2499,
		stock: 0,
		ageMin: 8,
		ageMax: null,
		deliveryDays: 3,
		tags: ['for-two-plus'],
		description:
			'Two difficulty levels on every card, so a child and a grandparent can play the same round.',
	},

	// Books
	{
		slug: 'atlas-of-space',
		name: 'Atlas of Space for Young Explorers',
		category: 'books',
		priceCents: 2200,
		stock: 24,
		ageMin: 7,
		ageMax: 12,
		deliveryDays: 2,
		tags: ['stem'],
		description:
			'Hardcover, 96 pages of planets, moons and missions, with a fold-out map of the solar system.',
	},
	{
		slug: 'dinosaur-encyclopedia',
		name: 'The Big Dinosaur Encyclopedia',
		category: 'books',
		priceCents: 2750,
		stock: 19,
		ageMin: 6,
		ageMax: 12,
		deliveryDays: 2,
		tags: ['stem'],
		description:
			'Over 200 species with life-size footprints and a timeline from the Triassic to the Cretaceous.',
	},
	{
		slug: 'bedtime-stories-365',
		name: 'Bedtime Stories for Every Night of the Year',
		category: 'books',
		priceCents: 1999,
		stock: 30,
		ageMin: 3,
		ageMax: 7,
		deliveryDays: 2,
		tags: ['cozy'],
		description:
			'365 five-minute stories, one for each date, illustrated in watercolor.',
	},
	{
		slug: 'coding-for-kids',
		name: 'Coding for Kids: Build Your First Game',
		category: 'books',
		priceCents: 1795,
		stock: 21,
		ageMin: 9,
		ageMax: 14,
		deliveryDays: 2,
		tags: ['stem'],
		description:
			'Step-by-step projects in a free block-based language, from a moving sprite to a platformer.',
	},
	{
		slug: 'weeknight-cookbook',
		name: 'Weeknight Cookbook: 100 Dinners in 30 Minutes',
		category: 'books',
		priceCents: 2900,
		stock: 17,
		ageMin: 16,
		ageMax: null,
		deliveryDays: 3,
		tags: ['adults'],
		description:
			'Recipes built around one pan and a shopping list of what most kitchens already have.',
	},
	{
		slug: 'fantasy-trilogy-box',
		name: 'Fantasy Trilogy, Hardcover Box Set',
		category: 'books',
		priceCents: 5400,
		stock: 9,
		ageMin: 12,
		ageMax: null,
		deliveryDays: 4,
		tags: ['teens'],
		description:
			'All three volumes in a slipcase with a map of the kingdom printed on the endpapers.',
	},
	{
		slug: 'lighthouse-keepers',
		name: 'The Lighthouse Keepers: Graphic Novel',
		category: 'books',
		priceCents: 1599,
		stock: 27,
		ageMin: 10,
		ageMax: null,
		deliveryDays: 2,
		tags: ['teens'],
		description:
			'Two siblings run a lighthouse through one winter storm. 180 full-color pages.',
	},

	// Arts & Crafts
	{
		slug: 'watercolor-set-36',
		name: 'Watercolor Set, 36 Colors with Brushes',
		category: 'arts-crafts',
		priceCents: 3200,
		stock: 23,
		ageMin: 8,
		ageMax: null,
		deliveryDays: 2,
		tags: ['creative'],
		description:
			'Half pans in a metal tin, three round brushes and a water brush for painting outside.',
	},
	{
		slug: 'sketchbook-a4',
		name: 'Sketchbook A4, 120 gsm, 100 Sheets',
		category: 'arts-crafts',
		priceCents: 1250,
		stock: 60,
		ageMin: 6,
		ageMax: null,
		deliveryDays: 1,
		tags: ['creative'],
		description:
			'Lies flat when open, acid-free paper that takes pencil, ink and light washes.',
	},
	{
		slug: 'air-dry-clay-kit',
		name: 'Air-Dry Clay Kit with Tools',
		category: 'arts-crafts',
		priceCents: 1900,
		stock: 29,
		ageMin: 6,
		ageMax: null,
		deliveryDays: 2,
		tags: ['creative', 'screen-free'],
		description:
			'1 kg of white clay, eight tools and six paints. Hardens in 24 hours without an oven.',
	},
	{
		slug: 'friendship-bracelet-kit',
		name: 'Friendship Bracelet Kit',
		category: 'arts-crafts',
		priceCents: 1600,
		stock: 33,
		ageMin: 7,
		ageMax: 14,
		deliveryDays: 2,
		tags: ['creative', 'for-two-plus'],
		description:
			'40 skeins of cotton thread, a braiding disc and a pattern book for 20 bracelets.',
	},
	{
		slug: 'oil-paint-starter',
		name: 'Oil Paint Starter Set, 12 Tubes',
		category: 'arts-crafts',
		priceCents: 4800,
		stock: 11,
		ageMin: 14,
		ageMax: null,
		deliveryDays: 3,
		tags: ['creative', 'adults'],
		description:
			'Twelve 21 ml tubes, four bristle brushes, a palette knife and odorless solvent.',
	},
	{
		slug: 'canvas-panels-6',
		name: 'Canvas Panels, 30×40 cm, 6-pack',
		category: 'arts-crafts',
		priceCents: 1800,
		stock: 40,
		ageMin: 8,
		ageMax: null,
		deliveryDays: 2,
		tags: ['creative'],
		description: 'Primed cotton on rigid board, ready for acrylic or oil.',
	},
	{
		slug: 'tabletop-easel',
		name: 'Tabletop Wooden Easel',
		category: 'arts-crafts',
		priceCents: 3400,
		stock: 8,
		ageMin: 8,
		ageMax: null,
		deliveryDays: 7,
		tags: ['creative'],
		description:
			'Beech, holds canvases up to 60 cm, with a drawer for paints and brushes.',
	},
	{
		slug: 'jumbo-crayons-16',
		name: 'Jumbo Crayons for Toddlers, 16 Colors',
		category: 'arts-crafts',
		priceCents: 999,
		stock: 55,
		ageMin: 2,
		ageMax: 5,
		deliveryDays: 1,
		tags: ['first-years', 'creative'],
		description:
			'Thick triangular crayons that do not roll off the table and wash off walls with water.',
	},

	// Science & STEM
	{
		slug: 'kids-microscope',
		name: 'Kids Microscope, 100×–1200×',
		category: 'science',
		priceCents: 6400,
		stock: 13,
		ageMin: 8,
		ageMax: null,
		deliveryDays: 4,
		tags: ['stem', 'battery-powered'],
		requires: ['aa-batteries-8'],
		description:
			'Metal body, LED light from above and below, 12 prepared slides. The light takes 2 AA; batteries not included.',
	},
	{
		slug: 'crystal-growing-kit',
		name: 'Crystal Growing Kit',
		category: 'science',
		priceCents: 2499,
		stock: 20,
		ageMin: 10,
		ageMax: null,
		deliveryDays: 3,
		tags: ['stem'],
		description:
			'Seven crystals in seven colors, grown over two weeks, with a display case.',
	},
	{
		slug: 'solar-robot-12in1',
		name: 'Solar Robot Kit, 12-in-1',
		category: 'science',
		priceCents: 2900,
		stock: 18,
		ageMin: 8,
		ageMax: null,
		deliveryDays: 3,
		tags: ['stem', 'outdoor'],
		description:
			'One set of parts builds twelve robots that run on sunlight. No batteries needed.',
	},
	{
		slug: 'electronics-starter-kit',
		name: 'Electronics Starter Kit, 100 Projects',
		category: 'science',
		priceCents: 4900,
		stock: 16,
		ageMin: 8,
		ageMax: null,
		deliveryDays: 3,
		tags: ['stem', 'battery-powered'],
		requires: ['aa-batteries-8'],
		description:
			'Snap-together parts on a base grid: a doorbell, a radio, a fan. Takes 2 AA; batteries not included.',
	},
	{
		slug: 'telescope-70mm',
		name: 'Refractor Telescope 70 mm with Tripod',
		category: 'science',
		priceCents: 11900,
		stock: 7,
		ageMin: 10,
		ageMax: null,
		deliveryDays: 9,
		tags: ['stem', 'outdoor'],
		description:
			'Shows the rings of Saturn and the moons of Jupiter. Aluminum tripod, two eyepieces, a phone adapter.',
	},
	{
		slug: 'volcano-kit',
		name: 'Volcano Science Kit',
		category: 'science',
		priceCents: 1750,
		stock: 34,
		ageMin: 6,
		ageMax: null,
		deliveryDays: 2,
		tags: ['stem'],
		description:
			'Paint a plaster volcano and make it erupt three times. Adult supervision recommended.',
	},
	{
		slug: 'coding-robot',
		name: 'Screen-Free Coding Robot',
		category: 'science',
		priceCents: 7900,
		stock: 0,
		ageMin: 5,
		ageMax: 9,
		deliveryDays: 4,
		tags: ['stem', 'screen-free', 'battery-powered'],
		requires: ['aaa-batteries-8'],
		description:
			'Kids program a route with arrow cards and the robot drives it. Takes 3 AAA; batteries not included.',
	},

	// Outdoor
	{
		slug: 'kick-scooter-light-up',
		name: 'Kick Scooter with Light-Up Wheels',
		category: 'outdoor',
		priceCents: 6900,
		stock: 10,
		ageMin: 5,
		ageMax: 12,
		deliveryDays: 4,
		tags: ['outdoor'],
		description:
			'Three height settings up to 50 kg. The wheels light up as they spin, no batteries.',
	},
	{
		slug: 'kids-bike-helmet',
		name: 'Kids Bike Helmet, Adjustable',
		category: 'outdoor',
		priceCents: 3200,
		stock: 24,
		ageMin: 3,
		ageMax: 10,
		deliveryDays: 2,
		tags: ['outdoor'],
		description:
			'Fits heads 48–56 cm with a dial at the back. Certified to EN 1078.',
	},
	{
		slug: 'delta-kite-140',
		name: 'Delta Kite, 140 cm',
		category: 'outdoor',
		priceCents: 2600,
		stock: 19,
		ageMin: 6,
		ageMax: null,
		deliveryDays: 3,
		tags: ['outdoor'],
		description:
			'Ripstop nylon with fiberglass spars, flies in light wind. 30 m of line on a handle.',
	},
	{
		slug: 'kids-binoculars',
		name: 'Kids Binoculars 8×21',
		category: 'outdoor',
		priceCents: 2700,
		stock: 22,
		ageMin: 5,
		ageMax: null,
		deliveryDays: 2,
		tags: ['outdoor', 'stem'],
		description:
			'Real glass optics, rubber armor that survives a drop, and a bird guide card.',
	},
	{
		slug: 'led-camping-lantern',
		name: 'LED Camping Lantern',
		category: 'outdoor',
		priceCents: 2900,
		stock: 17,
		ageMin: 8,
		ageMax: null,
		deliveryDays: 2,
		tags: ['outdoor', 'battery-powered', 'adults'],
		requires: ['aa-batteries-8'],
		description:
			'300 lumens, three modes, a hook for the tent ceiling. Takes 3 AA; batteries not included.',
	},
	{
		slug: 'flying-disc-175',
		name: 'Flying Disc, 175 g',
		category: 'outdoor',
		priceCents: 1300,
		stock: 50,
		ageMin: 6,
		ageMax: null,
		deliveryDays: 1,
		tags: ['outdoor', 'for-two-plus'],
		description:
			'Regulation weight for ultimate, soft enough to catch bare-handed.',
	},
	{
		slug: 'speed-jump-rope',
		name: 'Speed Jump Rope',
		category: 'outdoor',
		priceCents: 1100,
		stock: 38,
		ageMin: 8,
		ageMax: null,
		deliveryDays: 1,
		tags: ['outdoor'],
		description:
			'Ball-bearing handles and a steel cable, adjusts from 2 to 3 m without tools.',
	},

	// Tech
	{
		slug: 'kids-wireless-headphones',
		name: 'Kids Wireless Headphones, Volume-Limited',
		category: 'tech',
		priceCents: 4500,
		stock: 21,
		ageMin: 3,
		ageMax: 12,
		deliveryDays: 3,
		tags: ['travel'],
		description:
			'Capped at 85 dB, 30 hours per charge, folds flat for a backpack. USB-C cable included.',
	},
	{
		slug: 'instant-print-camera',
		name: 'Instant Print Camera',
		category: 'tech',
		priceCents: 7900,
		stock: 14,
		ageMin: 8,
		ageMax: null,
		deliveryDays: 3,
		tags: ['creative', 'teens'],
		requires: ['instant-film-20'],
		description:
			'Point, shoot and hold a print a minute later. Built-in rechargeable battery; film not included.',
	},
	{
		slug: 'waterproof-speaker',
		name: 'Bluetooth Speaker, Waterproof',
		category: 'tech',
		priceCents: 3900,
		stock: 26,
		ageMin: 10,
		ageMax: null,
		deliveryDays: 2,
		tags: ['outdoor', 'travel', 'teens'],
		description:
			'IP67, floats in a pool, 12 hours per charge. Pairs two speakers for stereo.',
	},
	{
		slug: 'lcd-drawing-tablet',
		name: 'LCD Drawing Tablet, 10 inch',
		category: 'tech',
		priceCents: 1999,
		stock: 44,
		ageMin: 3,
		ageMax: null,
		deliveryDays: 2,
		tags: ['creative', 'travel'],
		description:
			'Draw with the stylus, wipe with one button. Replaceable coin cell included, lasts about a year.',
	},
	{
		slug: 'star-projector',
		name: 'Star Projector Night Light',
		category: 'tech',
		priceCents: 3400,
		stock: 15,
		ageMin: 0,
		ageMax: null,
		deliveryDays: 3,
		tags: ['cozy', 'first-years'],
		description:
			'Projects a slowly turning night sky, turns itself off after 30 minutes. USB powered.',
	},
	{
		slug: 'e-ink-reader',
		name: 'E-Ink Reader, 6 inch',
		category: 'tech',
		priceCents: 11900,
		stock: 5,
		ageMin: 10,
		ageMax: null,
		deliveryDays: 5,
		tags: ['adults', 'travel'],
		description:
			'Glare-free screen with a warm front light, weeks per charge, holds thousands of books.',
	},

	// Home
	{
		slug: 'knitted-throw',
		name: 'Knitted Throw Blanket, 130×170 cm',
		category: 'home',
		priceCents: 5900,
		stock: 12,
		ageMin: null,
		ageMax: null,
		deliveryDays: 3,
		tags: ['cozy', 'adults'],
		description: 'Chunky cotton knit in oatmeal, washable at 30 °C.',
	},
	{
		slug: 'soy-candle-trio',
		name: 'Soy Candle Set, 3 Scents',
		category: 'home',
		priceCents: 3600,
		stock: 20,
		ageMin: 18,
		ageMax: null,
		deliveryDays: 2,
		tags: ['cozy', 'adults'],
		description:
			'Cedar, fig and sea salt in glass jars, about 35 hours of burn time each.',
	},
	{
		slug: 'stoneware-mug',
		name: 'Stoneware Mug, 400 ml',
		category: 'home',
		priceCents: 1800,
		stock: 48,
		ageMin: 6,
		ageMax: null,
		deliveryDays: 2,
		tags: ['cozy'],
		description:
			'Hand-glazed, so no two are the same. Dishwasher and microwave safe.',
	},
	{
		slug: 'tea-sampler-8',
		name: 'Loose Leaf Tea Sampler, 8 Tins',
		category: 'home',
		priceCents: 3200,
		stock: 16,
		ageMin: 16,
		ageMax: null,
		deliveryDays: 3,
		tags: ['cozy', 'adults'],
		description:
			'Two greens, two blacks, an oolong and three herbal blends, 25 g each, with a steel infuser.',
	},
	{
		slug: 'herb-grow-kit',
		name: 'Grow Your Own Herbs Kit',
		category: 'home',
		priceCents: 2400,
		stock: 25,
		ageMin: 6,
		ageMax: null,
		deliveryDays: 3,
		tags: ['stem', 'creative'],
		description:
			'Basil, parsley and chives in three ceramic pots, sprout in about ten days on a windowsill.',
	},
	{
		slug: 'linen-photo-album',
		name: 'Linen Photo Album, 60 Pages',
		category: 'home',
		priceCents: 2800,
		stock: 18,
		ageMin: null,
		ageMax: null,
		deliveryDays: 2,
		tags: ['cozy'],
		description:
			'Holds 240 prints at 10×15 cm, with glassine sheets between the pages.',
	},
]
